[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # Disable secret scanning for non-sensitive config values
  SECRETS_SCAN_OMIT_KEYS = "MODEL,LANGUAGE,VECTOR_STORE_ID,VERBOSE_OPENAI"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configure functions timeout (26 seconds for Pro, 10 for Free)
[functions]
  # Note: This requires a Pro plan for > 10 seconds
  # For free tier, functions will timeout at 10 seconds
  node_bundler = "esbuild"

# Headers to ensure API routes work correctly
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
